### ISSUE TITLE
Julia: problem with symengine and exponentials ?

### ISSUE THREAD

**Issue by albop** [EconForge/Dolang#12] opened 2016-11-03 23:20 UTC
The following example raises an error when run with SymEngine activated.

```
type dummytype
end

eqs = [:(1/exp(a)+b)]
args = [(:a,0)]
parms = [:b]

using Dolang

println( make_method(Der{1}, dummytype, eq, args, parms) )


code = make_method(Der{1}, dummytype, eq, args, parms, funname=:fun)
f = eval(code)

a = [1.0]
b = [0.0]

f(Der{1},dummytype(),a,b)      # doesn't work
```

By looking at the generated code, it appears that Symengine transforms exp(x) into E^x . I don't know if it's supposed to be a bug of symengine, nor what is the right way to fix it. As a quick fix one could define E as e in all functions. Are there other similar transformations ?

**Comment by albop** [comment] 2016-11-03 23:21
Sorry I don't have symengine on my machine currently so I don't know what the error message look like. I'll add it later if needed.

**Comment by spencerlyon2** [comment] 2016-11-04 00:31
Very good catch.

I looked in SymEngine.jl and it seems that the problem is known and they have a way around it: https://github.com/symengine/SymEngine.jl/blob/44c617328b31e340c2fa384eb4bdc47a85f41d8f/src/subs.jl#L29-L61

See the example:

```
julia> b = Basic(:(sin(x) + exp(y)))
E^y + sin(x)

julia> SymEngine.walk_expression(b)
:(e ^ y + sin(x))
```

We just need to call the `walk_expression` function on all of our `SymEngine.Basic` types to get the correct Julia version of the corresponding expressions

**Comment by spencerlyon2** [comment] 2016-11-04 00:36
Fixed in 3164b1ddb621e9f3bac433a452dcb588241cf489

See below:

```
julia> type dummytype
       end

julia> eqs = [:(1/exp(a)+b)]
1-element Array{Expr,1}:
 :(1 / exp(a) + b)

julia> args = [(:a,0)]
1-element Array{Tuple{Symbol,Int64},1}:
 (:a,0)

julia> parms = [:b]
1-element Array{Symbol,1}:
 :b

julia> using Dolang

julia> println( make_method(Der{1}, dummytype, eqs, args, parms) )
begin
    function anonymous!(::Dolang.TDer{1},::dummytype,out,V,p)
        begin
            if size(out) != (1,1)
                msg = "Expected out to be size $((1,1)), found $(size(out))"
                throw(DimensionMismatch(msg))
            end
            fill!(zero(eltype),out)
        end
        begin
            begin
                _b_ = p[1]
            end
            begin
                _a_ = V[1]
            end
            begin
                out[1] = -1 * e ^ (-1_a_)
            end
            return out
        end
    end
    function anonymous(::Dolang.TDer{1},::dummytype,V,p)
        out = zeros(Float64,(1,1))
        begin
            begin
                _b_ = p[1]
            end
            begin
                _a_ = V[1]
            end
            begin
                out[1] = -1 * e ^ (-1_a_)
            end
            return out
        end
    end
end
```

**Closed by spencerlyon2** 2016-11-04 00:36 UTC

**Comment by albop** [comment] 2016-11-04 16:06
Thanks, no idea what your code does though...

**Comment by spencerlyon2** [comment] 2016-11-04 16:28
Instead of just inserting the string version of SymEngine's representation of each expression (the one with the `E`), we now use their utilities to map SymEngine expressions into valid Julia expressions (i.e. their utilities know to replace `E` with `e`).

This is what that `SymEngine.walk_expression` function does
